### ISSUE TITLE
TRDP-SPY: Wireshark crash if XML is missing

### ISSUE THREAD

**Issue by onvav** [T12z/TCNopen#8]
Hello,
it seems that the Wireshark with trdp-spy plugin crashes at every start, when TRDP configuration file (saved at Preferences) is removed, moved or renamed.

Only workaround is to remove its path from file: `c:\Users\name.surname\AppData\Roaming\Wireshark\preferences`

Section:
```
# TRDP configuration file
# A path to a file
trdp.configfile: C:\path\to\removed\trdp_spy.xml
```

The Wireshark crashes without any error message or dialog. Only this I was able to get from command line:

```
** (wireshark:16148) 14:38:01.451158 [GLib CRITICAL] -- g_propagate_error: assertion 'src != NULL' failed
**
GLib:ERROR:../src/2.72.3-eda9959d65.clean/glib/gerror.c:1152:g_propagate_prefixed_error: assertion failed: (*dest != NULL)
Bail out! GLib:ERROR:../src/2.72.3-eda9959d65.clean/glib/gerror.c:1152:g_propagate_prefixed_error: assertion failed: (*dest != NULL)
```

Detected at:
- Windows 10
- Wireshark 4.0.4 64-bit
- Trdp-spy plugin 2.2.1

![trdp_spy_cfgXML](https://user-images.githubusercontent.com/12120327/230083876-fc3780e3-e8fb-49af-981c-b29d12e70d54.png)

**Comment by T12z** [comment]
Hej Ondrej,

then don't remove the xml-file while it is configured 😛 

Another workaround would be to take the plugin out of the plugin folder, start wireshark, which should reset the settings.

I guess the fix is a quicky to check for file-existence first, however it is always quite an effort for me to build the Windows-plugin binary. So don't count on it too soon.

Nevertheless, thanks for the report!!

**Comment by onvav** [comment]
Yep! I don't even touch the XML file anymore :-) It's trivial issue, but yes... better to check file/path existence and show warning then crashing Wireshark by NULL pointer.
Thx for great plugin! It helps our team a lot.
